[project]
name = 'another-sip009-nft'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.another-ape]
path = 'contracts/another-ape.clar'
clarity_version = 3
epoch = 3.1

[[project.requirements]]
contract_id = 'SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait'
# Clarinet uses this information to download the contract from the network and takes care of deploying it to local or test networks for your testing.

[contracts.sip009]
path = 'contracts/sip009.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
