[project]
name = 'tiny-market'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.sip009-nft]
path = 'contracts/sip009-nft.clar'
clarity_version = 3
epoch = 3.1

[contracts.sip009-nft-trait]
path = 'contracts/sip009-nft-trait.clar'
clarity_version = 3
epoch = 3.1

[contracts.sip010-nft]
path = 'contracts/sip010-nft.clar'
clarity_version = 3
epoch = 3.1

[contracts.sip010-nft-trait]
path = 'contracts/sip010-nft-trait.clar'
clarity_version = 3
epoch = 3.1

[contracts.sip010-token]
path = 'contracts/sip010-token.clar'
clarity_version = 3
epoch = 3.1

[contracts.tiny-market]
path = 'contracts/tiny-market.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
